name: "Entity detection"

validation_data:
  dataset: "abisee/cnn_dailymail"
  input_feature: "article"
  split_name: "validation"
  dataset_version: "1.0.0"

results:
  output_cached: true
  bad_request_default_value: -1
  output_cache_id: "id"

preprocessor:
  entries: ["example_tool.fizzbuzz", "example_tool.replace_text_with_length", "example_tool.count_ands"]

llm:
  model: "azure/gpt-4o"
  temperature: 0
  sprompt: |
    You are the best in the world to do summarizations. Please, when given a text, do the best to summarize it.
  uprompt: |
    This text is fizzbuzzed in this way: {{ data.fizzbuzz }}.
    This text contains this many `and`s: {{ data.and_countes }}.
    Please write as a first line the fizzbuzzed text. As a second line, follow with the number of `and`s.
    The third line follow as the summary of this:
    {{ data.article }}